_wandb:
    value:
        cli_version: 0.21.1
        e:
            li1oqm7gkcv6r42d7zpfn019wu52eobk:
                codePath: wandb_agent.py
                codePathLocal: wandb_agent.py
                email: jm.parraullauri@bristol.ac.uk
                executable: /Users/te22204/git/Ollama-Search-Agent/myenv/bin/python3
                git:
                    commit: 94351b20767266be5070a89969448320d1dd6397
                    remote: https://github.com/JuanMaParraU/Ollama-Search-Agent.git
                host: MJPFWPXGYL
                os: macOS-15.6.1-arm64-arm-64bit-Mach-O
                program: /Users/te22204/git/Ollama-Search-Agent/wandb_agent.py
                python: CPython 3.13.2
                root: /Users/te22204/git/Ollama-Search-Agent
                startedAt: "2025-08-28T16:21:51.621148Z"
                writerId: li1oqm7gkcv6r42d7zpfn019wu52eobk
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 105
            "2":
                - 86
                - 105
            "3":
                - 13
                - 16
            "4": 3.13.2
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
framework:
    value: langgraph
max_tokens:
    value: 500
model:
    value: mistral-nemo
temperature:
    value: 0
